name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Format
        run: cargo fmt --all -- --check
      - name: Install Linux X11 dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            libdbus-1-dev \
            libssl-dev \
            libwxgtk3.*-dev \
            libx11-dev \
            libxkbcommon-dev \
            libxtst-dev
      - name: Build
        run: |
          cargo build \
            --no-default-features \
            --features modulo,vendored-tls
      - name: Test
        run: |
          cargo test \
            --workspace \
            --exclude espanso-modulo \
            --exclude espanso-ipc \
            --no-default-features \
            --features vendored-tls
      - name: Clippy
        run: cargo clippy --all-targets --features=modulo,vendored-tls -- --deny warnings

  linux-wayland:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Format
        run: cargo fmt --all -- --check
      - name: Install Linux wayland dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            libdbus-1-dev \
            libssl-dev \
            libwxgtk3.*-dev \
            libxkbcommon-dev \
            wl-clipboard
      - name: Build
        run: |
          cargo build \
            --no-default-features \
            --features modulo,vendored-tls,wayland
      - name: Test
        run: |
          cargo test \
            --workspace \
            --exclude espanso-modulo \
            --exclude espanso-ipc \
            --no-default-features \
            --features vendored-tls,wayland
      - name: Clippy
        run: cargo clippy --features=modulo,vendored-tls,wayland -- --deny warnings

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Install target
        run: |
          rustup update
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: |
          cargo build --target aarch64-apple-darwin
          cargo build --target x86_64-apple-darwin
      - name: Clippy
        run: |
          cargo clippy --target=aarch64-apple-darwin -- --deny warnings
          cargo clippy --target=x86_64-apple-darwin -- --deny warnings

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: |
          cargo build
      - name: Clippy
        run: cargo clippy -- --deny warnings
